from setuptools import setup, find_packages

setup(
    name="student-lms-ai-backend",
    version="1.0.0",
    description="A FastAPI-based Learning Management System with AI capabilities",
    author="Your Name",
    author_email="your.email@example.com",
    packages=find_packages(where="app"),
    package_dir={"": "app"},
    python_requires=">=3.11",
    install_requires=[
        "fastapi>=0.104.1",
        "uvicorn>=0.24.0",
        "sqlalchemy>=2.0.23",
        "psycopg2-binary>=2.9.9",
        "python-jose[cryptography]>=3.3.0",
        "passlib[bcrypt]>=1.7.4",
        "python-multipart>=0.0.6",
        "alembic>=1.12.1",
        "pydantic>=2.4.2",
        "pydantic-settings>=2.0.0",
        "python-dotenv>=1.0.0",
        "email-validator>=2.1.0.post1",
    ],
    extras_require={
        "dev": [
            "pytest>=7.4.3",
            "pytest-cov>=4.1.0",
            "black>=23.12.1",
            "ruff>=0.2.1",
            "mypy>=1.8.0",
            "httpx>=0.25.2",
        ],
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Education",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.11",
        "Programming Language :: Python :: 3.12",
        "Topic :: Education",
        "Framework :: FastAPI",
    ],
    entry_points={
        "console_scripts": [
            "student-lms=app.main:start_app",
        ],
    },
    include_package_data=True,
    zip_safe=False,
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    url="https://github.com/yourusername/student_lms_ai_backend",
    project_urls={
        "Bug Tracker": "https://github.com/yourusername/student_lms_ai_backend/issues",
        "Documentation": "https://github.com/yourusername/student_lms_ai_backend/docs",
        "Source Code": "https://github.com/yourusername/student_lms_ai_backend",
    },
    keywords=[
        "education",
        "lms",
        "fastapi",
        "ai",
        "learning-management-system",
        "python",
        "backend",
    ],
)
