"""Add clarification_questions column to Activity

Revision ID: e06be39f2403
Revises: 
Create Date: 2025-06-04 01:23:05.154287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e06be39f2403'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_templates')
    op.add_column('activity', sa.Column('clarification_questions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity', 'clarification_questions')
    op.create_table('activity_templates',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sub_category_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('difficulty_level', postgresql.ENUM('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='difficultylevel'), autoincrement=False, nullable=False),
    sa.Column('access_type', postgresql.ENUM('PRIVATE', 'GLOBAL', name='accesstype'), autoincrement=False, nullable=False),
    sa.Column('final_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['activity_categories.id'], name='activity_templates_category_id_fkey'),
    sa.ForeignKeyConstraint(['sub_category_id'], ['activity_sub_categories.id'], name='activity_templates_sub_category_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='activity_templates_pkey')
    )
    # ### end Alembic commands ###
